defaults: &defaults
   country_categories:
      TAIWAN: 'NTD'
      AMERICA : 'USD'
      EUROPE: 'EUR'
      JAPAN: 'JPY'
      HONKONG: 'HKD'
      ENGLAND: 'GBP'
      AUSTRALIA: 'AUD'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
